spring.application.name=tuneturtle

#Mongo DB Configuration
spring.data.mongodb.uri=mongodb://kvskaushik_Admin:3MxACXgvzHnCBXn4@ac-pcaamsh-shard-00-00.luzt2ep.mongodb.net:27017,ac-pcaamsh-shard-00-01.luzt2ep.mongodb.net:27017,ac-pcaamsh-shard-00-02.luzt2ep.mongodb.net:27017/tuneturleAdmin?ssl=true&replicaSet=atlas-xvqs6l-shard-0&authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.database=tuneturleAdmin


#Cloudinary Configuration
cloudinary.cloud-name=dd2ahsrg0
cloudinary.api-key=157262376955821
cloudinary.api-secret=PLHfxQDlyWzHb5eJ7vaTfmiMSTM

#File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


#JWT Configuration
jwt.secret=MySecretKeyForTuneTurtleMusicPlatformForEmergingArtists
# 24 hours jwt token will be active
jwt.expiration=86400000

#Razorpay Configuration
razorpay.key.id=YOUR_RAZORPAY_KEY_ID
razorpay.key.secret=YOUR_RAZORPAY_KEY_SECRET