spring.application.name=tuneturtle

#Mongo DB Configuration
spring.data.mongodb.uri=mongodb+srv://kvskaushik_Admin:3MxACXgvzHnCBXn4@cluster0.luzt2ep.mongodb.net/tuneturleAdmin?retryWrites=true&w=majority
spring.data.mongodb.database=tuneturleAdmin


#Cloudinary Configuration
cloudinary.cloud-name=dd2ahsrg0
cloudinary.api-key=157262376955821
cloudinary.api-secret=PLHfxQDlyWzHb5eJ7vaTfmiMSTM

#File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


#JWT Configuration
jwt.secret=MySecretKeyForTuneTurtleMusicPlatformForEmergingArtists
# 24 hours jwt token will be active
jwt.expiration=86400000